### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by small-bamboo** [ZimmermanGroup/pyGSM#24]
I follow you introduction ,but it gives a error
***************************************************************************************88
Traceback (most recent call last):
  File "/home/ybw/anaconda3/bin/gsm", line 33, in <module>
    sys.exit(load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')())
  File "/home/ybw/anaconda3/bin/gsm", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/ybw/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/ybw/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ybw/anaconda3/lib/python3.8/site-packages/pyGSM-0.1-py3.8.egg/pygsm/wrappers/main.py", line 21, in <module>
    from growing_string_methods import *
  File "/home/ybw/anaconda3/lib/python3.8/site-packages/pyGSM-0.1-py3.8.egg/pygsm/growing_string_methods/__init__.py", line 1, in <module>
    from .de_gsm import DE_GSM
  File "/home/ybw/anaconda3/lib/python3.8/site-packages/pyGSM-0.1-py3.8.egg/pygsm/growing_string_methods/de_gsm.py", line 15, in <module>
    from main_gsm import MainGSM
ModuleNotFoundError: No module named 'main_gsm'

**Comment by small-bamboo** [comment]
i solve that ,but a new error occurs 
###################################
 from geodesic_interpolate import redistribute
ModuleNotFoundError: No module named 'geodesic_interpolate'
##############################################

what should i pip?

**Comment by small-bamboo** [comment]
Is the source code missing？

**Comment by craldaz** [comment]
I've removed this dependency in this commit  6579477b2ed9232a31220bdb53b282628fe901c4
