### ISSUE TITLE
pyGSM requires xib, although it is installed and is not requested

### ISSUE THREAD

**Issue by mit-eremin** [ZimmermanGroup/pyGSM#43]
Reinstalled pyGSM (did not run it locally for over a year) and it fails to run. when I tell `gsm -h` it gives the following message. Also, same happens when I try to run an actually calculation specifying the package. xTB is installed in the environment and can be run.

`
(dft) Dmitrys-MacBook-Pro:~ eremin$ gsm -h
ASE not installed, ASE-based calculators will not work
Traceback (most recent call last):
  File "/opt/anaconda3/envs/dft/bin/gsm", line 33, in <module>
    sys.exit(load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')())
  File "/opt/anaconda3/envs/dft/bin/gsm", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/anaconda3/envs/dft/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/opt/anaconda3/envs/dft/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/anaconda3/envs/dft/lib/python3.9/site-packages/pygsm/wrappers/main.py", line 18, in <module>
    from pygsm.level_of_theories.xtb_lot import xTB_lot
  File "/opt/anaconda3/envs/dft/lib/python3.9/site-packages/pygsm/level_of_theories/xtb_lot.py", line 7, in <module>
    from xtb.interface import Calculator
ModuleNotFoundError: No module named 'xtb'
`

**Comment by ms860309** [comment]
Hi, you can try to install xtb-python, it might help.
