### ISSUE TITLE
SE xtb job with submission to cluster via SGE scheduler

### ISSUE THREAD

**Issue by tanoury1** [ZimmermanGroup/pyGSM#52]
Hi, I'm trying to run a SE xtb job using pyGSM.  I have used GSM for several years and am switching to pyGSM.
In addition to the SGE stuff required for my submit script, I am using:

gsm  -xyzfile reactants.xyz \
    -isomers isomers.txt \
    -mode SE_GSM \
    -package xTB_lot \
    -ID $SGE_TASK_ID \
    -coordinate_type DLC > log 2>&1

ID=`printf "%0*d\n" 4 ${SGE_TASK_ID}`

In my error file, I'm getting
"File "/cluster/home/tanoury/.local/lib/python3.7/site-packages/pyGSM-0.1-py3.7.egg/pygsm/level_of_theories/xtb_lot.py", line 8, in <module>
    from xtb.interface import Calculator
ModuleNotFoundError: No module named 'xtb'

When I try to run each line of xtb_lot.py in my conda environment in via command line, I'm getting:
(gsm) [tanoury@tanourylnx:~]$ python
Python 3.9.17 | packaged by conda-forge | (main, Aug 10 2023, 07:02:31) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> from os import path
>>> import numpy as np
>>> from xtb.interface import Calculator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cluster/home/tanoury/miniconda3/envs/gsm/lib/python3.9/site-packages/xtb/interface.py", line 20, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
>>> 

Additionally, when running an xtb job, do I need a "-lot_input_file"?

Thank you for your help.
Jerry

**Comment by tanoury1** [comment]
Hi, this is no longer an issues.

Jerry
